version: "3.5"

networks:
  monitoring:
    name: monitoring

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    user: 1000:1000
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ~/monitoring/prometheus/data:/prometheus
      - ~/monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    restart: unless-stopped
    ports: 
      - 8285:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /mnt/windows_docker:/rootfs/var/lib/docker:ro
    devices:
      - /dev/kmsg
    privileged: true
    networks:
      - monitoring
