global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  #  -  "first.rules"

scrape_configs:
  - job_name: 'SAGAN-windows'
    static_configs:
      - targets: ['localhost:9182']
  - job_name: 'SAGAN-docker'
    static_configs:
      - targets: ['cadvisor:8285']
